import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const dirs = ['start', 'theory', 'roles', 'adopters', 'dev', 'reference'];
const sidebars: SidebarsConfig = {
  docsSidebar: dirs.map((dirName) => ({
    type: 'category',
    label: dirName[0].toUpperCase() + dirName.slice(1),
    items: [{ type: 'autogenerated', dirName }],
  })),
};

export default sidebars;
