/** Schemas reachable from the current CLI and its runtime services. */
export const ROSTER = [
  'action-registry.schema.json',
  'action-result.schema.json',
  'actions-list-output.schema.json',
  'authority-policy.schema.json',
  'authority-session.schema.json',
  'check-suites.schema.json',
  'common-defs.schema.json',
  'error.schema.json',
  'evidence.schema.json',
  'forbidden-actions.schema.json',
  'glob-guards.schema.json',
  'invariant.schema.json',
  'inventory.schema.json',
  'local-evidence-manifest.schema.json',
  'meta.schema.json',
  'model-runtime-registry.schema.json',
  'mutation-scenario.schema.json',
  'phase-closure.schema.json',
  'proof-epoch.schema.json',
  'record-meta.schema.json',
  'release-control.schema.json',
  'repo-introspection.schema.json',
  'round-execution.schema.json',
  'runtime-charter.schema.json',
  'scorecard-na-config.schema.json',
  'scorecard.schema.json',
  'sense-presets.schema.json',
  'sensor-reading.schema.json',
  'sensor-registry.schema.json',
  'subprocess-effects.schema.json',
  'task-execution-evidence.schema.json',
  'task.schema.json',
  'trace.schema.json',
  'translation-witness.schema.json',
  'validation-result.schema.json',
] as const;

export type SchemaName = (typeof ROSTER)[number] | (string & {});

export const INFRASTRUCTURE: readonly SchemaName[] = [
  'common-defs.schema.json',
  'record-meta.schema.json',
];
