// The explicit schema roster (W02.c: explicitness is a feature; laziness is the mechanic).
// 54 contract schemas + 3 infrastructure (common-defs, record-meta, meta).
// Guarded: the roster-dir bijection is a T2 contract; cardinality derives from the directory.
export const ROSTER = [
  'action-registry.schema.json',
  'actions-evidence-gate-authorization.schema.json',
  'actions-list-output.schema.json',
  'adr.schema.json',
  'agent-run.schema.json',
  'api-map.schema.json',
  'assessment.schema.json',
  'authority-policy.schema.json',
  'authority-session.schema.json',
  'common-defs.schema.json',
  'coverage-matrix.schema.json',
  'data-model-inventory.schema.json',
  'dep-graph.schema.json',
  'error.schema.json',
  'evidence.schema.json',
  'forbidden-actions.schema.json',
  'genesis-attestation.schema.json',
  'glob-guards.schema.json',
  'glossary-entry.schema.json',
  'inv-candidate.schema.json',
  'inv-override.schema.json',
  'invariant.schema.json',
  'inventory.schema.json',
  'journey.schema.json',
  'local-evidence-manifest.schema.json',
  'meta.schema.json',
  'module-blueprint.schema.json',
  'mutation-intent.schema.json',
  'phase-closure.schema.json',
  'population-registry.schema.json',
  'project-config.schema.json',
  'prompt-composition.schema.json',
  'proof-epoch.schema.json',
  'rbac-inventory.schema.json',
  'record-meta.schema.json',
  'release-control.schema.json',
  'repo-introspection.schema.json',
  'rgr.schema.json',
  'round-close-manifest.schema.json',
  'routes-inventory.schema.json',
  'rtd-manifest.schema.json',
  'runtime-charter.schema.json',
  'scorecard-na-config.schema.json',
  'scorecard.schema.json',
  'sensor-input-spec.schema.json',
  'sensor-registry.schema.json',
  'sensor-reading.schema.json',
  'skill-manifest.schema.json',
  'stack-adapter.schema.json',
  'subprocess-effects.schema.json',
  'task.schema.json',
  'test-weakening-config.schema.json',
  'trace.schema.json',
  'translation-witness.schema.json',
  'triage.schema.json',
  'use-cases.schema.json',
  'validation-result.schema.json',
] as const;
export type SchemaName = (typeof ROSTER)[number];
export const INFRASTRUCTURE: readonly SchemaName[] = [
  'common-defs.schema.json',
  'record-meta.schema.json',
  'meta.schema.json',
];
