import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, describe, expect, it } from 'vitest';
import { buildCloseoutMd } from '../../src/skills/round/closeout.js';
import {
  computeScorecardDelta,
  findNextFreeRoundN,
  readOpenBlockersForRound,
  readWaveLogStatuses,
  scorecardCellId,
} from '../../src/skills/round/state.js';
import {
  findWavePromptFile,
  isUnbackedWave,
  MANDATORY_MIN_GATES,
  parseWaveCatalog,
  parseWavePromptHeader,
  pollWaveLog,
  readWaveLogStatus,
  resolveDevaiCliBin,
  resolveGateCommand,
  runGate,
  writeWaveLog,
} from '../../src/skills/round/waves.js';
import { withAuthorityHostTestScope } from './authority-host-test-scope.js';

const roots: string[] = [];

function root(): string {
  const path = mkdtempSync(join(tmpdir(), 'devai-round-utils-'));
  roots.push(path);
  return path;
}

function put(base: string, relativePath: string, contents: string): string {
  const path = join(base, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  return path;
}

afterEach(() => {
  delete process.env['DEVAI_CLI_BIN'];
  for (const path of roots.splice(0)) rmSync(path, { recursive: true, force: true });
});

describe('round wave parsing and discovery', () => {
  it('parses valid catalog rows while ignoring headings, headers, zero, and malformed rows', () => {
    const parsed = parseWaveCatalog(
      [
        '# Before',
        '| 9 | ignored | before section | Owner | low | - |',
        '## Wave catalog',
        '| # | slug | goal | role | effort | dependsOn |',
        '|---|---|---|---|---|---|',
        '| 0 | orchestrator | control | Owner | high | - |',
        '| bad | ignored | malformed | Owner | low | - |',
        '| 1 | `alpha` | first | Engineer | low | - |',
        '| 2 | beta | second | Inspector | high | 1 |',
        'not a table row',
        '## Next',
        '| 3 | ignored | after section | Owner | low | 2 |',
      ].join('\n'),
    );
    expect(parsed).toEqual([
      { num: 1, slug: 'alpha', goal: 'first', role: 'Engineer', effort: 'low', dependsOn: '-' },
      { num: 2, slug: 'beta', goal: 'second', role: 'Inspector', effort: 'high', dependsOn: '1' },
    ]);
    expect(parseWaveCatalog('# no catalog')).toEqual([]);
  });

  it('parses quoted frontmatter fields and ignores malformed or absent headers', () => {
    expect(
      parseWavePromptHeader(
        [
          '---',
          'role: "Inspector"',
          "effort: 'high'",
          'skill_id: SKILL-triage',
          'bad-key: ignored',
          'empty:',
          '---',
          'body',
        ].join('\n'),
      ),
    ).toEqual({ role: 'Inspector', effort: 'high', skill_id: 'SKILL-triage' });
    expect(parseWavePromptHeader('body only')).toEqual({});
  });

  it('distinguishes unbacked prompts from dispatch, skill, body, attribution, and unreadable cases', () => {
    const repo = root();
    expect(isUnbackedWave(put(repo, 'plain.md', '# plain'))).toBe(true);
    expect(
      isUnbackedWave(put(repo, 'dispatch.md', '---\ndispatch: local\n---\nbody')),
    ).toBe(false);
    expect(
      isUnbackedWave(put(repo, 'skill.md', '---\nskill_id: SKILL-triage\n---\nbody')),
    ).toBe(false);
    expect(isUnbackedWave(put(repo, 'body.md', 'Run SKILL-triage now.'))).toBe(false);
    expect(
      isUnbackedWave(put(repo, 'attribution.md', 'Auto-generated by SKILL-round-backlog')),
    ).toBe(true);
    const broken = join(repo, 'broken.md');
    symlinkSync(join(repo, 'absent'), broken);
    expect(isUnbackedWave(broken)).toBe(false);
  });

  it('finds prompt prefixes and reads every wave-log state fail-closed', async () => {
    const repo = root();
    const prompts = join(repo, 'prompts');
    expect(findWavePromptFile(prompts, 1)).toBeNull();
    put(prompts, '01-alpha.txt', 'wrong');
    put(prompts, '01-alpha.md', 'right');
    expect(findWavePromptFile(prompts, 1)).toBe(join(prompts, '01-alpha.md'));
    expect(findWavePromptFile(prompts, 2)).toBeNull();

    expect(readWaveLogStatus(join(prompts, 'absent.log'))).toBe('not_present');
    for (const status of [
      'clean',
      'blocked',
      'aborted',
      'dispatched',
      'in_progress',
      'not-dispatched',
    ] as const) {
      const path = put(prompts, `${status}.log`, `**Status:** ${status.toUpperCase()}`);
      expect(readWaveLogStatus(path)).toBe(status);
    }
    const unknown = put(prompts, 'unknown.log', 'no status');
    expect(readWaveLogStatus(unknown)).toBe('in_progress');
    const broken = join(prompts, 'broken.log');
    symlinkSync(join(prompts, 'missing'), broken);
    expect(readWaveLogStatus(broken)).toBe('not_present');
    expect(await pollWaveLog(put(prompts, 'done.log', '**Status:** clean'), 20, 1)).toBe('clean');
    expect(await pollWaveLog(join(prompts, 'never.log'), 2, 1)).toBe('timeout');
  });

  it('writes minimal wave logs with default and explicit summaries through authority', async () => {
    const repo = root();
    mkdirSync(join(repo, 'prompts'), { recursive: true });
    await withAuthorityHostTestScope(() => {
      const first = join(repo, 'prompts/01-alpha.log');
      writeWaveLog(first, { roundN: '0002', waveNum: 1, slug: 'alpha', status: 'dispatched' });
      expect(readFileSync(first, 'utf8')).toContain('_Minimal log written');
      const second = join(repo, 'prompts/02-beta.log');
      writeWaveLog(second, {
        roundN: 2,
        waveNum: 2,
        slug: 'beta',
        status: 'blocked',
        summary: 'blocked by fixture',
      });
      expect(readFileSync(second, 'utf8')).toContain('blocked by fixture');
    });
  });
});

describe('round gate resolution and execution', () => {
  it('prefers a valid CLI override and otherwise resolves the installed CLI', () => {
    const repo = root();
    const override = put(repo, 'devai-cli.js', '');
    process.env['DEVAI_CLI_BIN'] = override;
    expect(resolveDevaiCliBin(repo)).toBe(override);
    process.env['DEVAI_CLI_BIN'] = join(repo, 'absent');
    expect(resolveDevaiCliBin(repo)).toMatch(/packages\/cli\/dist\/bin\.js$/);
  });

  it('handles project opt-outs, strings, objects, malformed values, defaults, and unknown gates', () => {
    const repo = root();
    put(
      repo,
      '.devai/config/project.json',
      JSON.stringify({
        hardFailGates: {
          opted: null,
          empty: '',
          string: 'pnpm test --filter demo',
          object: { cmd: 'node', args: ['-e', 1, 'process.exit(0)'] },
          invalid: { cmd: '', args: 'wrong' },
        },
      }),
    );
    expect(resolveGateCommand('opted', repo)).toMatchObject({
      source: 'project-config',
      reason: expect.stringContaining('opted-out'),
    });
    expect(resolveGateCommand('empty', repo)).toMatchObject({ source: 'project-config' });
    expect(resolveGateCommand('string', repo)).toMatchObject({
      argv: ['pnpm', 'test', '--filter', 'demo'],
      source: 'project-config',
    });
    expect(resolveGateCommand('object', repo)).toMatchObject({
      command: 'node -e process.exit(0)',
      argv: ['node', '-e', 'process.exit(0)'],
    });
    expect(resolveGateCommand('invalid', repo)).toMatchObject({
      source: 'devai-default',
      reason: expect.stringContaining('unknown gate'),
    });
    expect(resolveGateCommand('lint', repo)).toMatchObject({
      command: 'pnpm lint',
      source: 'devai-default',
    });
    expect(resolveGateCommand('docs-links', repo)).toMatchObject({
      source: 'devai-default',
      cliBin: expect.stringMatching(/dist\/bin\.js$/),
    });
    expect(resolveGateCommand('unknown', repo)).toMatchObject({
      reason: expect.stringContaining('unknown gate'),
    });
    put(repo, '.devai/config/project.json', '{');
    expect(resolveGateCommand('test', repo)).toMatchObject({ command: 'pnpm test' });
    expect(MANDATORY_MIN_GATES).toContain('action-coverage');
  });

  it('returns not-configured evidence and executes a successful configured command', async () => {
    const repo = root();
    expect(runGate('unknown', repo, { sourceOverride: 'extra-gate' })).toMatchObject({
      status: 'not-configured',
      evidence: { source: 'extra-gate', status: 'not-configured' },
    });
    put(
      repo,
      '.devai/config/project.json',
      JSON.stringify({
        hardFailGates: {
          fixture: { cmd: process.execPath, args: ['-e', 'process.exit(0)'] },
        },
      }),
    );
    await withAuthorityHostTestScope(() => {
      expect(runGate('fixture', repo, { runId: 'fixture' })).toMatchObject({
        status: 'pass',
        evidence: {
          gate: 'fixture',
          status: 'pass',
          source: 'project-config',
          exit_code: 0,
        },
      });
    });
  });
});

describe('round state and closeout rendering', () => {
  it('finds free round numbers and reads matching open blockers and wave logs', () => {
    const repo = root();
    expect(findNextFreeRoundN(repo)).toBe(1);
    mkdirSync(join(repo, 'work/rounds/R-0002'), { recursive: true });
    mkdirSync(join(repo, 'work/rounds/R-0010'), { recursive: true });
    mkdirSync(join(repo, 'work/rounds/not-round'), { recursive: true });
    expect(findNextFreeRoundN(repo)).toBe(11);
    expect(readOpenBlockersForRound(repo, 2)).toEqual([]);
    put(
      repo,
      '.devai/state/decisions.jsonl',
      [
        JSON.stringify({
          id: 'DEC-1',
          kind: 'escalate',
          status: 'open',
          subject: 'round',
          description: 'root blocker',
          context: { round_id: 'R2' },
        }),
        JSON.stringify({
          id: 'DEC-2',
          kind: 'escalate',
          status: 'open',
          subject: 'wave',
          description: 'wave blocker',
          context: { round_id: 'R2-W3' },
        }),
        JSON.stringify({
          id: 'DEC-3',
          kind: 'escalate',
          status: 'closed',
          context: { round_id: 'R2' },
        }),
        '{',
      ].join('\n'),
    );
    expect(readOpenBlockersForRound(repo, 2)).toEqual([
      { id: 'DEC-1', subject: 'round', description: 'root blocker' },
      {
        id: 'DEC-2',
        subject: 'wave',
        description: 'wave blocker',
        waveId: 'R2-W3',
      },
    ]);

    const prompts = join(repo, 'prompts');
    expect(readWaveLogStatuses(prompts)).toEqual([]);
    put(prompts, '00-orchestrator.log', '**Status:** clean');
    put(prompts, '01-alpha.log', '**Status:** clean');
    put(prompts, '10-zeta.log', '**Status:** blocked');
    put(prompts, 'ignored.txt', '');
    expect(readWaveLogStatuses(prompts)).toEqual([
      { wave: 'W1', status: 'clean' },
      { wave: 'W10', status: 'blocked' },
    ]);
  });

  it('computes scorecard ids and deltas across missing, legacy, added, and changed cells', () => {
    expect(scorecardCellId({ substrate: 'F1', property: 'T2' })).toBe('F1×T2');
    expect(scorecardCellId({ id: 'legacy' })).toBe('legacy');
    expect(scorecardCellId({})).toBe('(?)');
    expect(
      computeScorecardDelta(
        { cells: [{ substrate: 'F1', property: 'T1', verdict: 'FAIL' }, { id: 'gone' }] },
        { cells: [{ substrate: 'F1', property: 'T1', verdict: 'PASS' }, { id: 'new' }] },
      ),
    ).toEqual({
      flipped: [
        { cell: 'F1×T1', before: 'FAIL', after: 'PASS' },
        { cell: 'gone', before: '?', after: '(absent)' },
        { cell: 'new', before: '(absent)', after: '?' },
      ],
      before_count: 2,
      after_count: 2,
    });
    expect(computeScorecardDelta(null, undefined)).toEqual({
      flipped: [],
      before_count: 0,
      after_count: 0,
    });
  });

  it('renders both empty and populated closeout branches and all gate glyphs', () => {
    const empty = buildCloseoutMd({
      roundN: '0002',
      goal: 'Coverage',
      verdict: 'clean',
      closingCommits: [],
      gateResults: [],
      scorecardDelta: { flipped: [], before_count: 0, after_count: 0 },
      waveStatuses: [],
      blockers: [],
    });
    expect(empty).toContain('to be set on commit');
    expect(empty).toContain('no gates re-run');
    expect(empty).toContain('no waves detected');
    expect(empty).toContain('_None._');

    const populated = buildCloseoutMd({
      roundN: 2,
      goal: 'Coverage',
      verdict: 'partial',
      closingCommits: ['abc', 'def'],
      gateResults: [
        { gate: 'lint', status: 'pass' },
        { gate: 'test', status: 'fail' },
        { gate: 'docs', status: 'not-configured' },
      ],
      scorecardDelta: {
        flipped: [{ cell: 'F1×T1', before: 'FAIL', after: 'PASS' }],
        before_count: 1,
        after_count: 1,
      },
      waveStatuses: [{ wave: 'W1', status: 'clean' }],
      blockers: [
        { id: 'DEC-1', subject: 'subject', description: 'description', waveId: 'R2-W1' },
      ],
    });
    expect(populated).toContain('Gates: 1 pass / 1 fail / 1 not-configured');
    expect(populated).toContain('✓ pass');
    expect(populated).toContain('✗ fail');
    expect(populated).toContain('∅ not-configured');
    expect(populated).toContain('`abc`, `def`');
    expect(populated).toContain('F1×T1');
    expect(populated).toContain('(R2-W1)');
  });
});
