import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from '@devai-nyx/authority';
import { dirname, join, resolve } from 'node:path';
import type { CAC } from 'cac';
import { EXIT_FAIL, EXIT_PASS } from '@devai-nyx/utils';
import {
  defineCommand,
  getFullRegistry,
  type ActionAuthority,
  type CommandSpec,
} from '../../define-command.js';

const DEFAULT_REPO_ROOT = process.cwd();
const DEFAULT_OUT_DIR = 'docs/reference/cli';

interface Options {
  readonly repoRoot?: string;
  readonly emitDir?: string;
  readonly check?: boolean;
  readonly human?: boolean;
}

interface ActionEntry extends CommandSpec {
  readonly noun: string;
  readonly verb: string | null;
  readonly extended_doc?: string;
  readonly runtime_args?: string;
  readonly runtime_options?: readonly { readonly flags: string; readonly description: string }[];
}

function appendRuntimeContract(lines: string[], action: ActionEntry): void {
  lines.push('### Usage');
  lines.push('');
  lines.push('```text');
  lines.push(
    `devai ${action.name}${action.runtime_args === undefined || action.runtime_args.length === 0 ? '' : ` ${action.runtime_args}`}`,
  );
  lines.push('```');
  lines.push('');
  if ((action.runtime_options?.length ?? 0) > 0) {
    lines.push('### Options');
    lines.push('');
    lines.push('| Flag | Description |');
    lines.push('|---|---|');
    for (const option of action.runtime_options ?? []) {
      lines.push(`| \`${option.flags}\` | ${option.description.replace(/\|/g, '\\|')} |`);
    }
    lines.push('');
  }
}

const AUTHORITY_LABEL: Record<ActionAuthority, string> = {
  mesh_controller: 'Mesh controller',
  specifier: 'Specifier',
  constructor: 'Constructor',
  sensor: 'Sensor',
  policy_firewall: 'Policy firewall',
  release_controller: 'Release controller',
  agent_runtime: 'Agent runtime',
  host_tooling: 'Host tooling',
};

function actionPageSlug(noun: string): string {
  return `${noun}.md`;
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

/**
 * Render the top-level docs/reference/cli/README.md: every action grouped
 * by authority, with a row per action linking to its noun page.
 */
function renderIndex(actions: readonly ActionEntry[]): string {
  const byAuthority = new Map<ActionAuthority | 'untagged', ActionEntry[]>();
  for (const a of actions) {
    const key = a.authority ?? 'untagged';
    const arr = byAuthority.get(key) ?? [];
    arr.push(a);
    byAuthority.set(key, arr);
  }
  const lines: string[] = [];
  lines.push('# DEVAI CLI reference');
  lines.push('');
  lines.push(
    '**Auto-generated by `devai docs cli --write`.** Do not hand-edit; the byte-identity gate will flag drift.',
  );
  lines.push('');
  lines.push(`Total registered actions: **${String(actions.length)}**.`);
  lines.push('');
  lines.push('## By authority');
  lines.push('');
  const authorityOrder: Array<ActionAuthority | 'untagged'> = [
    'mesh_controller',
    'specifier',
    'constructor',
    'sensor',
    'policy_firewall',
    'release_controller',
    'agent_runtime',
    'host_tooling',
    'untagged',
  ];
  for (const auth of authorityOrder) {
    const arr = byAuthority.get(auth);
    if (arr === undefined || arr.length === 0) continue;
    const label = auth === 'untagged' ? 'Untagged' : (AUTHORITY_LABEL[auth] ?? auth);
    lines.push(`### ${label} (${String(arr.length)} action${arr.length === 1 ? '' : 's'})`);
    lines.push('');
    lines.push('| Action | Description |');
    lines.push('|---|---|');
    for (const a of arr.slice().sort((x, y) => compareText(x.name, y.name))) {
      const desc = a.description.replace(/\|/g, '\\|');
      lines.push(`| [\`${a.name}\`](${actionPageSlug(a.noun)}) | ${desc} |`);
    }
    lines.push('');
  }
  lines.push('## By domain');
  lines.push('');
  const nouns = Array.from(new Set(actions.map((a) => a.noun))).sort(compareText);
  lines.push('| Domain | Reference |');
  lines.push('|---|---|');
  for (const n of nouns) {
    lines.push(`| \`${n}\` | [${actionPageSlug(n)}](${actionPageSlug(n)}) |`);
  }
  lines.push('');
  lines.push('## See also');
  lines.push('');
  lines.push(
    '- [`../../adopters/user-guide.md`](../../adopters/user-guide.md) — narrative introduction.',
  );
  lines.push(
    '- [`../../adopters/adoption.md`](../../adopters/adoption.md) — adopting DEVAI in a fresh client repo.',
  );
  lines.push('- [`../../roles/`](../../roles/) — which role is allowed to invoke which actions.');
  lines.push('- `devai catalog actions --format human` — live enumeration from the registry.');
  lines.push('');
  return lines.join('\n');
}

/**
 * Render one docs/reference/cli/<noun>.md page: the noun's verbs in order,
 * each with name + description + authority.
 */
function renderNounPage(noun: string, actions: readonly ActionEntry[]): string {
  const lines: string[] = [];
  lines.push(`# \`devai ${noun}\``);
  lines.push('');
  lines.push(
    '**Auto-generated by `devai docs cli --write`.** Do not hand-edit; the byte-identity gate will flag drift.',
  );
  lines.push('');
  const sorted = actions.slice().sort((a, b) => compareText(a.name, b.name));
  if (sorted.length === 1 && sorted[0]?.verb === null) {
    const a = sorted[0];
    lines.push(`## \`${a.name}\``);
    lines.push('');
    if (a.authority !== undefined) {
      lines.push(`**Authority:** ${AUTHORITY_LABEL[a.authority]}.`);
      lines.push('');
    }
    lines.push(
      `**Lifecycle:** ${a.lifecycle}. **Visibility:** ${a.visibility}. **Effects:** ${a.effects}.`,
    );
    lines.push('');
    lines.push(`**Profiles:** ${a.profiles.join(', ')}.`);
    lines.push('');
    lines.push(a.description);
    lines.push('');
    appendRuntimeContract(lines, a);
    if (a.extended_doc !== undefined) {
      lines.push(a.extended_doc);
      if (!a.extended_doc.endsWith('\n')) lines.push('');
    }
  } else {
    for (const a of sorted) {
      lines.push(`## \`${a.name}\``);
      lines.push('');
      if (a.authority !== undefined) {
        lines.push(`**Authority:** ${AUTHORITY_LABEL[a.authority]}.`);
        lines.push('');
      }
      lines.push(
        `**Lifecycle:** ${a.lifecycle}. **Visibility:** ${a.visibility}. **Effects:** ${a.effects}.`,
      );
      lines.push('');
      lines.push(`**Profiles:** ${a.profiles.join(', ')}.`);
      lines.push('');
      lines.push(a.description);
      lines.push('');
      appendRuntimeContract(lines, a);
      if (a.extended_doc !== undefined) {
        lines.push(a.extended_doc);
        if (!a.extended_doc.endsWith('\n')) lines.push('');
      }
    }
  }
  lines.push('## See also');
  lines.push('');
  lines.push('- [CLI reference index](./) — complete action inventory.');
  lines.push('');
  return lines.join('\n');
}

function generate(actions: readonly ActionEntry[]): Map<string, string> {
  const out = new Map<string, string>();
  out.set('README.md', renderIndex(actions));
  const byNoun = new Map<string, ActionEntry[]>();
  for (const a of actions) {
    const arr = byNoun.get(a.noun) ?? [];
    arr.push(a);
    byNoun.set(a.noun, arr);
  }
  for (const [noun, arr] of byNoun) {
    out.set(actionPageSlug(noun), renderNounPage(noun, arr));
  }
  return out;
}

function readCurrent(dir: string): Map<string, string> {
  const m = new Map<string, string>();
  if (!existsSync(dir)) return m;
  let names: string[];
  try {
    names = readdirSync(dir).filter((n) => n.endsWith('.md'));
  } catch {
    return m;
  }
  for (const n of names) {
    try {
      m.set(n, readFileSync(join(dir, n), 'utf8'));
    } catch {
      // skip unreadable
    }
  }
  return m;
}

export const docsCli = defineCommand({
  name: 'docs cli',
  description:
    'Generate the CLI reference under docs/reference/cli/ from the action catalog. --check fails on drift (byte-identity gate, Phase 13.C).',
  authority: 'mesh_controller',
  register(cli: CAC): void {
    cli
      .command('docs-cli', 'Generate or check the CLI reference under docs/reference/cli/')
      .option('--repo-root <path>', `Repo root (default: ${DEFAULT_REPO_ROOT})`)
      .option('--emit-dir <path>', `Output dir (default: ${DEFAULT_OUT_DIR})`)
      .option(
        '--check',
        'Do not write; exit non-zero if regenerated content differs from the committed files',
      )
      .option('--human', 'Human-readable summary')
      .action((options: Options) => {
        const repoRoot = resolve(options.repoRoot ?? DEFAULT_REPO_ROOT);
        const outDir = resolve(repoRoot, options.emitDir ?? DEFAULT_OUT_DIR);
        const actions: ActionEntry[] = getFullRegistry().map((a) => ({
          ...a,
          noun: a.path[0] ?? 'unknown',
          verb: a.path.length > 1 ? a.path.slice(1).join(' ') : null,
        }));
        const desired = generate(actions);

        if (options.check === true) {
          const current = readCurrent(outDir);
          const drift: string[] = [];
          for (const [name, want] of desired) {
            const have = current.get(name);
            if (have === undefined) drift.push(`${name}: missing`);
            else if (have !== want) drift.push(`${name}: byte mismatch`);
          }
          for (const have of current.keys()) {
            if (!desired.has(have)) drift.push(`${have}: orphan file`);
          }
          if (drift.length === 0) {
            process.stdout.write(
              options.human === true
                ? `docs cli --check: OK (${String(desired.size)} file(s) match)\n`
                : JSON.stringify({ ok: true, files: desired.size }) + '\n',
            );
            process.exitCode = EXIT_PASS;
            return;
          } else {
            const payload = { ok: false, drift };
            process.stdout.write(
              options.human === true
                ? `docs cli --check: DRIFT (${String(drift.length)} issue(s))\n` +
                    drift.map((d) => `  - ${d}`).join('\n') +
                    '\n'
                : JSON.stringify(payload) + '\n',
            );
            process.exitCode = EXIT_FAIL;
            return;
          }
        }

        // Emit mode.
        try {
          mkdirSync(outDir, { recursive: true });
          // Clean up orphan files first.
          const existing = readdirSync(outDir).filter((n) => n.endsWith('.md'));
          for (const n of existing) {
            if (!desired.has(n)) {
              try {
                rmSync(join(outDir, n));
              } catch {
                // best-effort
              }
            }
          }
          for (const [name, content] of desired) {
            writeFileSync(join(outDir, name), content);
          }
          if (options.human === true) {
            process.stdout.write(`docs cli: wrote ${String(desired.size)} file(s) to ${outDir}\n`);
          } else {
            process.stdout.write(
              JSON.stringify({ ok: true, files: desired.size, out_dir: outDir }) + '\n',
            );
          }
          process.exitCode = EXIT_PASS;
        } catch (err) {
          process.stderr.write(
            `devai docs cli: ${err instanceof Error ? err.message : String(err)}\n`,
          );
          process.exit(EXIT_FAIL);
        }
      });
  },
});

// Quiet unused imports
void dirname;
